### ISSUE TITLE
Cannot getCurrentPosition on iOS

### ISSUE THREAD

**Issue by davbaron** [BaseflowIT/flutter-geolocator#192] opened 2019-02-14 06:52 UTC
## 🐛 Bug Report

As illustrated in a prior issue, #184 , I am unable to get a value back from getCurrentPosition. On advice, I issued the checkGeolocationPermissionStatus() call first, and it comes back as 'granted'.  I had already checked the iOS 'privacy/location services' settings and they were 'good'.

Here is the code again:
```
Future _initGeoLocatorPlatformState() async {

Position position;
GeolocationStatus geolocationStatus  = await Geolocator().checkGeolocationPermissionStatus();
print ("geolocationStatus is: $geolocationStatus.toString()");
if (geolocationStatus == GeolocationStatus.granted) {
   try {
    final Geolocator geolocator = Geolocator()
      ..forceAndroidLocationManager = true;
    position = await geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
    print('gotCurrentPosition: ' + position.latitude.toString() + " : " + position.longitude.toString());
  } on PlatformException {
    position = null;
    print("getCurrentPosition had a PlatformException");
  }
} else {
  position = null;
  print("checkGeolocationPermissionStatus is NOT granted");
}

// If the widget was removed from the tree while the asynchronous platform
// message was in flight, we want to discard the reply rather than calling
// setState to update our non-existent appearance.
if (!mounted) {
  return;
}

setState(() {
  _curPosition = position;
});

}
```
Stepping into the code, I can see that the geolocator object *is* non-null. The exception occurs as soon as the getCurrentPosition call is made. I have tried numerous LocationAccuracy values, all with the same result.

My app *also* has the Flutter Google_Maps plug-in, which works fine. Not sure if that matters or not.

### Expected behavior
Get back valid position.

### Reproduction steps
See above code.

### Configuration

**Version:** ^3.0.0  

**Platform:** 
- [ x] :iphone: iOS 12.1
- [ ] :robot: Android

**Comment by mvanbeusekom** [comment] 2019-02-14 09:09
I am really sorry @davbaron but I cannot reproduce this problem. I have copied your code and inserted it into the default app template (made sure I call the function when the state object is constructed). The code runs fine and I don't run into any exceptions.

Could you get some more details on the exception? Something like this would help:

```dart
   try {
    final Geolocator geolocator = Geolocator()
      ..forceAndroidLocationManager = true;
    position = await geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);
    print('gotCurrentPosition: ' + position.latitude.toString() + " : " + position.longitude.toString());
  } catch(PlatformException ex) {
    position = null;
    print("getCurrentPosition had a PlatformException: ${ex.message}");
    print("Error details: ${ex.details}");
  }
```

**Comment by davbaron** [comment] 2019-02-14 19:01
Thank you Maurits, for your suggestion.  I ran the 'catch' code and it showed the following error:   
getCurrentPosition had a PlatformException: The operation couldn’t be completed. (kCLErrorDomain error 0.)

I did some research and it seems that if you are using an iOS simulator (like I am), then you MUST select a 'location' within the Debug : Location : <sub-menu>.  My sub-menu had two options, "None" and "Custom".  Neither was selected.  If "None" is selected it definitely will not work.  I selected the 'Custom' option, and a dialog came up with my current location.  I 'accepted' it, and then re-ran my project.  Sure enough getCurrentPosition came back with the same values that the simulator suggested as my default/current location.

I imagine you can close this ticket, but I will leave it to you. I am not an iOS expert, but do not understand how the simulator, which *can* seem to access the internet via my home wifi, cannot get a current location without one being 'defaulted'. Maybe this is just how it works... and once on a real phone it will work great. Thank you again for hanging in there with me.

**Comment by mvanbeusekom** [comment] 2019-02-14 19:52
Good to hear you managed to solve it. The reason could very well be the simulator, it is a bit limited. I will close the issue for now, however if you experience problems again don't hesitate to leave a message.

**Closed by mvanbeusekom** 2019-02-14 19:52 UTC
