### ISSUE TITLE
Get location in Foreground

### ISSUE THREAD

**Issue by JackLillie** [BaseflowIT/flutter-geolocator#273] opened 2019-05-28 13:50 UTC
## 🚀 Feature Requests

I would like to be able to get the current location in the foreground, while the app is running.

### Describe the feature

I have an app that gets the users current location every 10 seconds and plots a point on a map and draws a polyline from those locations, I got it working fine on iOS but on Android it isn't able to get the current location when the app isn't the main app open, for example, if you go to a different app, or lock your screen, it stops getting the location.

### Platforms affected (mark all that apply)
- [ x] :iphone: iOS
- [ x] :robot: Android

**Comment by mvanbeusekom** [comment] 2019-05-28 13:53
@JackLillie I think you mean that you want to get the location in the backgroup (not foreground as mentioned in your request)? If this is the case, this would be a duplicate of #53.

**Comment by JackLillie** [comment] 2019-05-28 13:55
> @JackLillie I think you mean that you want to get the location in the backgroup (not foreground as mentioned in your request)? If this is the case, this would be a duplicate of #53.

Yeah, I just need to get the location as long as the app is running, I don't need it if the app is closed. Close if this is a duplicate.

**Closed** 2019-05-28 13:57 UTC
