### ISSUE TITLE
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.

### ISSUE THREAD

**Issue by prasant10050** [BaseflowIT/flutter-geolocator#217] opened 2019-03-01 17:16 UTC
## 🐛 Bug Report

 `google_api_availability` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

### Configuration

**Version:** 3

**Platform:** 
- [x] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment] 2019-03-05 11:52
Duplicate of #219

**Closed by mvanbeusekom** 2019-03-05 11:52 UTC
Labels: bug
