### ISSUE TITLE
Why does it need so much Purpose String in Info.plist File

### ISSUE THREAD

**Issue by kvacquier** [BaseflowIT/flutter-geolocator#169] opened 2019-01-16 13:53 UTC
Hello.
I just moved to this library and I've got tons of warning from apple :

> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSContactsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSCalendarsUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSAppleMusicUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSMotionUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 
> Missing Purpose String in Info.plist File - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSSpeechRecognitionUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data will be required to include a purpose string.If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).
> 

Do you know why you use so much data ? why a geolocator need apple music informations or SpeechRecognition or even Contacts

**Comment by mvanbeusekom** [comment] 2019-01-23 09:15
@kvacquier, @nicolasvac, this is an unfortunate side effect of our `permission_handler` plugin which simplifies requesting access to services which need user consent. This plugin touches all the SDKs and thus when run through Apples analytic tools, Apple thinks we (you) are actually accessing all SDKs requiring all the purpose strings to be present.

We are currently working on a fix and hopefully be able to release a better version soon. Will keep you updated.

**Comment by japborst** [comment] 2019-04-28 19:16
Anybody having the same issues, this was fixed in v4.0.0

**Comment by mvanbeusekom** [comment] 2019-04-29 07:06
as mentioned by @japborst, this issue is fixed in v4.0.0. We swapped the `permission_handler` with the new `location_permissions` plugin.

**Closed by mvanbeusekom** 2019-04-29 07:06 UTC

**Comment by silversquall** [comment] 2019-05-20 15:44
> @kvacquier, @nicolasvac, this is an unfortunate side effect of our `permission_handler` plugin which simplifies requesting access to services which need user consent. This plugin touches all the SDKs and thus when run through Apples analytic tools, Apple thinks we (you) are actually accessing all SDKs requiring all the purpose strings to be present.
> 
> We are currently working on a fix and hopefully be able to release a better version soon. Will keep you updated.

@mvanbeusekom : did you it in recent permission_handler's build ? (i'm having the issue with v 3.0.0)

**Comment by mvanbeusekom** [comment] 2019-05-20 16:29
@silversquall the problem is the `permission_handler` plugin. That is the reason we swapped it in the `geolocator` plugin for the `location_permissions` plugin. 

The `permission_handler` plugin is still touching all SDKs, the idea is to create a separate plugin for each permission so you can selectively add support for specific permissions.

**Comment by daninfpj** [comment] 2019-05-22 13:21
I submitted an app to the App Store using version `4.0.3` and still got the email from Apple saying `NSLocationAlwaysUsageDescription` was missing from `Info.plist` even though we never request that permission.
