### ISSUE TITLE
FAILURE: Build failed with an exception

### ISSUE THREAD

**Issue by alann-maulana** [BaseflowIT/flutter-geolocator#122] opened 2018-10-06 02:34 UTC
## 🐛 Bug Report

FAILURE: Build failed with an exception.

**From Flutter Project**
```
What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not resolve com.google.android.gms:play-services-location:15.+.
  Required by:
      project :app > project :geolocator
      project :app > project :google_api_availability
```

**Tools > Flutter > Open Android module in Android Studio**
```
Unable to resolve dependency for ':geolocator@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-places-placereport:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-places-placereport:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-places-placereport:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@release/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@release/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@release/compileClasspath': Could not resolve com.google.android.gms:play-services-places-placereport:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@release/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@releaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@releaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@releaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-places-placereport:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':geolocator@releaseUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debug/compileClasspath': Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.71.
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-places-placereport:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debug/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debugAndroidTest/compileClasspath': Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.71.
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-places-placereport:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debugAndroidTest/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debugUnitTest/compileClasspath': Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.71.
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-places-placereport:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@debugUnitTest/compileClasspath': Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@release/compileClasspath': Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.71.
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@release/compileClasspath': Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@release/compileClasspath': Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
Open File
Show Details


Unable to resolve dependency for ':google_api_availability@release/compileClasspath': Could not resolve com.google.android.gms:play-services-places-placereport:[15.0.1,16.0.0).
Open File
```

### Reproduction steps

1. Create new Flutter project from Android Studio
2. Add flutter-geolocator into dependencies
```
dependencies:
  geolocator: ^2.0.1

```
3. Compile and run

### Configuration

**flutter doctor -v**
```shell
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.14 18A391, locale en-ID)
    • Flutter version 0.8.2 at /Users/Maulana/Development/flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/Maulana/Development/AndroidSDK
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5616
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Version:** 2.0.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment] 2018-10-06 06:29
Hi @alann-maulana, 

I cannot reproduce this error. Here is what I am doing:

1. Open Android Studio;
2. Create a new Flutter Application project;
3. In the wizard I only changed the value for the `Project Location`;
4. Click `Finish` to create the project;
5. Once the project is created I open the `pubspec.yaml` file
6. Add the line `geolocator: ^2.0.1` directly underneath `flutter` dependecy. Like so:
```
dependencies:
  flutter:
    sdk: flutter

  geolocator: ^2.0.1
```
7. Hit the `Packages get` link (top right of Android Studio file editor)
8. Hit the debug icon to compile and start debugging

Using these steps, the app starts without any problems in the simulator. Below you'll find a screenshot and the `flutter doctor -v` output for the two environments in which I tested.

I will be closing this issue for now, if you have more information don't hesitate to leave a post and we will try to debug this further.

<img width="1680" alt="screenshot 2018-10-06 at 08 07 01" src="https://user-images.githubusercontent.com/13098888/46568243-c3cf4c80-c941-11e8-9654-771ef9587018.png">

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.14 18A391, locale en-NL)
    • Flutter version 0.8.2 at /Users/maurits/Developer/flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/maurits/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /Users/maurits/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 28.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.3911.37

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

```
$ flutter doctor -v
[✓] Flutter (Channel beta, v0.8.2, on Mac OS X 10.14 18A391, locale en-NL)
    • Flutter version 0.8.2 at /Users/maurits/Developer/flutter
    • Framework revision 5ab9e70727 (4 weeks ago), 2018-09-07 12:33:05 -0700
    • Engine revision 58a1894a1c
    • Dart version 2.1.0-dev.3.1.flutter-760a9690c2

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.0)
    • Android SDK at /Users/maurits/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.0
    • ANDROID_HOME = /Users/maurits/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.2
    • Dart plugin version 181.5540.11
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 27.1.3
    • Dart plugin version 182.3911.37

[✓] VS Code (version 1.27.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
```

**Closed by mvanbeusekom** 2018-10-06 06:29 UTC

**Comment by daimionsg** [comment] 2018-10-06 23:56
I've been getting a similar error since the most recent update to:
Kotlin Plugin Version: 1.2.71-release-Studio3.2-1
Android Studio Version: 3.2

When opening as a Flutter project it works, and can run on the emulator. Opening just the android module in android studio, gets the following - "Unsupported Modules Detected: Compilation is not supported for following modules: geolocator. Unfortunately you can't have non-Gradle Java modules and Android-Gradle modules in one project."

It then displays the list of "Unable to resolve...." 

If using the geolocator version 2.0.1, the error is for both permission_handler and google_api_availability. If I revert back to geolocator version 1.7.0, the error is just for permission_handler.

My error messages are slightly different
![image](https://user-images.githubusercontent.com/40311454/46576778-e2e2e280-ca04-11e8-8136-99c8f55a9f80.png)

**Comment by alann-maulana** [comment] 2018-11-17 04:39
@mvanbeusekom I have solved this issue by changing flutter channel from `beta` to `master` and upgrading both gradle and flutter to the latest version.
